
services:
  postgres:
    image: postgres:16
    container_name: billing-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data # сохраняем данные на локальном диске
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
